version: '3'

services:
  alfresco:
    image: hub.xenit.eu/alfresco-enterprise:5.1
    restart: unless-stopped
    ports:
    - 8080
    environment:
    - SOLR_HOST=solr

  solr:
    image: ${DOCKER_IMAGE}
    ports:
    - 8443
    restart: unless-stopped
    hostname: solr
    environment:
    - ALFRESCO_HOST=alfresco

  jodconverter:
    image: hub.xenit.eu/jodconverter-ws:build-12
    restart: unless-stopped

  postgresql:
    image: hub.xenit.eu/postgres:0.0.1-24
    restart: unless-stopped
    environment:
    - POSTGRES_USER=alfresco
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=alfresco
    restart: unless-stopped

