version: '3'

services:
  alfresco-sharded:
    image: hub.xenit.eu/alfresco-enterprise:5.1
    restart: unless-stopped
    ports:
    - 8080
    volumes:
    - ./license51:/opt/alfresco/license
    environment:
    - DB_URL=jdbc:postgresql://postgresql-sharded:5432/alfresco
    - SOLR_HOST=solr1-sharded
    - SOLR_SSL=none
    - ENABLE_CLUSTERING=true
    - DYNAMIC_SHARD_REGISTRATION=true    
    - GLOBAL_dir.license.external=/opt/alfresco/license

  solr1-sharded:
    image: ${DOCKER_IMAGE}
    restart: unless-stopped
    ports:
    - 8080
    hostname: solr1-sharded
    environment:
    - ALFRESCO_HOST=alfresco-sharded
    - SOLR_HOST=solr1-sharded
    - ALFRESCO_SSL=none
    - ARCHIVE_ENABLE_ALFRESCO_TRACKING=false
    - ARCHIVE_INDEX_CONTENT=false
    - ALFRESCO_INDEX_CONTENT=false
    - MAX_HTTP_HEADER_SIZE=65536
    - SHARDING=true
    - SHARD_IDS=0,1
    - SHARD_METHOD=DB_ID    
    - CORE_NAME=alfresco    
    - NUM_SHARDS=3
    - NUM_NODES=2
    - NODE_INSTANCE=1
    - TEMPLATE=rerank

  solr2-sharded:
    image: ${DOCKER_IMAGE}
    restart: unless-stopped
    ports:
    - 8080
    hostname: solr2-sharded
    environment:
    - ALFRESCO_HOST=alfresco-sharded
    - SOLR_HOST=solr2-sharded
    - ALFRESCO_SSL=none
    - ARCHIVE_ENABLE_ALFRESCO_TRACKING=false
    - ARCHIVE_INDEX_CONTENT=false
    - ALFRESCO_INDEX_CONTENT=false
    - MAX_HTTP_HEADER_SIZE=65536
    - SHARDING=true
    - SHARD_IDS=2
    - SHARD_METHOD=DB_ID    
    - CORE_NAME=alfresco
    - NUM_SHARDS=3
    - NUM_NODES=2
    - NODE_INSTANCE=2
    - TEMPLATE=rerank

  postgresql-sharded:
    image: hub.xenit.eu/postgres:0.0.1-24
    restart: unless-stopped
    environment:
    - POSTGRES_USER=alfresco
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=alfresco
    restart: unless-stopped
